### ISSUE TITLE
Doesn't allow to cancel, when you answer an asking for dynas

### ISSUE THREAD

**Issue by lopesdynamix** [yuribett/DynaClub#39]
**Doesn't allow to cancel**, when you answer an asking for dynas.
![image](https://cloud.githubusercontent.com/assets/21042431/24667673/a69182e0-193a-11e7-908d-1b205fab72de.png)

**Comment by anderson-amorim** [comment]
This behavior is intended. The user already has the option to deny the request and if one choose to accept, this action should be definitive.
