### ISSUE TITLE
After canceling donations, donation fields refresh as mandatory

### ISSUE THREAD

**Issue by lopesdynamix** [yuribett/DynaClub#41]
When I **donate dynas** to someone and I **cancel it** a few seconds later, the app doesn't adjust the donation buttons behaviours.
So, if I does not fill all mandatory donation fields, the **submit button is available to click on**, showing some errors.
![image](https://cloud.githubusercontent.com/assets/21042431/25014813/b4db17d2-204f-11e7-8916-10e8752ea4f4.png)

**Comment by anderson-amorim** [comment]
Duplicated of #37 
The same issue is causing both of the problems

**Comment by lopesdynamix** [comment]
It's still happening.
