### ISSUE TITLE
'Meus Dynas' menor que zero

### ISSUE THREAD

**Issue by silviogneto** [yuribett/DynaClub#46]
Quando o valor dos 'Meus Dynas' chega a zero ainda é possível enviar dynas.
![image](https://cloud.githubusercontent.com/assets/7586634/26013543/5821cec2-372f-11e7-9d6c-35f011c39c3c.png)

**Comment by anderson-amorim** [comment]
@lopesdynamix Esse problema provavelmente ja foi resolvido nos ajustes feitos no form de envio. Podes confirmar se acontece no QA?

**Comment by anderson-amorim** [comment]
@silviogneto Bug fixed within the version 0.4.6, released today.
